feat: Posibility of executate the interpreter for read a file and get it tokens
Hint-Box/Ezcript pull request #9
Opened 2021-04-09 22:26 UTC by FRostri

2021-04-09 23:21 UTC, Sebastian-byte requested changes

2021-04-09 23:21 UTC, Sebastian-byte commented on README.md
> +You can executate the interpreter for now like this: `./ezcript`
execute*

2021-04-09 23:21 UTC, Sebastian-byte commented on ezcript
> +            elif arg[-3:] != '.ez' and arg[0:2] != '--' and arg[0:1] != '-':
I think it should support any file extension.

2021-04-09 23:21 UTC, Sebastian-byte commented on ezcript_lang/repl.py
> +    # commanf for mac and linux
command*, macOS*

2021-04-09 23:21 UTC, Sebastian-byte commented on ezcript_lang/repl.py
> +    # command for windows
Windows* (capitalize it).

2021-04-09 23:37 UTC, FRostri commented on ezcript
> +            elif arg[-3:] != '.ez' and arg[0:2] != '--' and arg[0:1] != '-':
You think so? Couldn't we get into trouble later on?

2021-04-10 00:41 UTC, Sebastian-byte commented on ezcript
> +            elif arg[-3:] != '.ez' and arg[0:2] != '--' and arg[0:1] != '-':
Many compilers and interpreters ignores the extension, like GCC, Clang or Python.

2021-04-10 00:43 UTC, Sebastian-byte commented on ezcript
> +            elif arg[-3:] != '.ez' and arg[0:2] != '--' and arg[0:1] != '-':
A warning should be ok, not a error.

2021-04-10 00:54 UTC, FRostri commented on ezcript
> +            elif arg[-3:] != '.ez' and arg[0:2] != '--' and arg[0:1] != '-':
Ooh, all right, I'll leave it then

2021-04-10 02:31 UTC, FRostri commented
@Sebastian-byte Is ready

2021-04-10 21:20 UTC, Sebastian-byte approved these changes

2021-04-11 05:36 UTC, merged

2021-04-11 18:26 UTC, Sebastian-byte commented
Perdón presione el botón por accidente 😭

2021-04-12 03:37 UTC, FRostri commented
ae, no te preocupes ya la vuelvo a crear XD